### ISSUE TITLE
dsr_dsrlnkraw.c:49: error: impossible constraint in ‘asm’

### ISSUE THREAD

**Issue by mburkley** [tursilion/libti99#24]
Just FYI, I've getting a build error in dsr_dsrlnkraw.c with tms9900-gcc that I haven't noticed before :

dsr_dsrlnkraw.c: In function ‘dsrlnkraw’:
dsr_dsrlnkraw.c:49: warning: asm operand 1 probably doesn’t match constraints
dsr_dsrlnkraw.c:49: error: impossible constraint in ‘asm’

It seems it doesn't like the "immediate" constraint for buf on line 106 as buf isn't a constant?

       : "i" (buf)

My fix was 

  #define NAME_BUF 0x8380
 : "i" (NAME_BUF)

**Comment by tursilion** [comment]
That's odd, I've been building repeatedly the last couple weeks and I don't have any issues.

~/gcc9900/bin/tms9900-gcc -c dsr_dsrlnkraw.c -O2 -std=c99 -s --save-temp -I./ -fno-builtin -o dsr_dsrlnkraw.o

Is it a difference in GCC version? When did you last update your patches?

There are new patches now available over on the original AtariAge thread, though I was also building with the previous set by Insomnia.

I think before I touch anything we need to know what changed on your side. :)

**Comment by mburkley** [comment]
Interesting, I don't see it either with -O2.  But I do see it without -O2.

**Comment by XZCE** [comment]
Even with GCC 10.3.0 (~2021) which is the latest GCC I use (for the Pi Pico - and is for arm, but can still try to compile to assembly [-S] on this file) this error occurs if optimisation is not turned on, because without it, buf can't be considered a constant.  Even making it "unsigned char * const buf" isn't enough without optimisation, which surprised me.

Telling GCC it's a r/register or p/pointer will work by putting it into a register from the stack, but it will use R1 which is used by the custom assembly code that's there.  The original suggestion of making it a true constant would seem the best way forward.

**Comment by tursilion** [comment]
I'm not sure where you are getting your TMS9900 GCC, but the latest supported patches are for GCC 9.4.0. We've been making a lot of fixes lately at the AtariAge forums.

That said, if you want to submit a patch that'd be fine. I haven't tested file access for quite a while. I'll be deprecating this version of libti99 sometime in the near future, but I can port the fix forward.
